addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.3.2")
addSbtPlugin("com.github.tkawachi"  % "sbt-doctest"     % "0.9.9")
addSbtPlugin("com.eed3si9n"         % "sbt-unidoc"      % "0.4.3")
addSbtPlugin("de.heikoseeberger"    % "sbt-header"      % "5.4.0")
addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.7")
addSbtPlugin("ch.epfl.scala" % "sbt-scala3-migrate" % "0.5.1")