name: build

on: [push, pull_request]

jobs:
  
  tests:
    name: scala-${{ matrix.scala }} jdk-${{ matrix.java }} tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        java: [11]
        scala: [2.12.14, 2.13.8, 3.1.2]

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: Cache SBT Coursier directory
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - name: Cache SBT directory
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: |
            ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}-${{ hashFiles('project/plugins.sbt') }}
          restore-keys: ${{ runner.os }}-sbt-

      - name: Run checks
        run:  sbt scalafmtCheckAll
      - name: Run Unit Tests for Java ${{ matrix.java }}, Scala ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} test
